[package]
name = "utena"
version = "0.1.0"
authors = ["eleonora tennyson <dev@tennyson.io>"]
edition = "2024"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
zellij-tile = "0.42.2"

